kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: config-policy-controller
subjects:
- kind: ServiceAccount
  name: config-policy-controller
  namespace: open-cluster-management-agent-addon
roleRef:
  kind: ClusterRole
  name: config-policy-controller
  apiGroup: rbac.authorization.k8s.io
