apiVersion: apps/v1
kind: Deployment
metadata:
  name: governance-policy-spec-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      name: governance-policy-spec-sync
  template:
    metadata:
      labels:
        name: governance-policy-spec-sync
    spec:
      serviceAccountName: governance-policy-spec-sync
      containers:
        - name: governance-policy-spec-sync
          image: quay.io/open-cluster-management/governance-policy-spec-sync:latest-2.4
          command:
          - governance-policy-spec-sync
          args:
            - '--hub-cluster-configfile=/var/run/klusterlet/kubeconfig'
          imagePullPolicy: Always
          volumeMounts:
            - name: klusterlet-config
              mountPath: /var/run/klusterlet
          env:
            - name: WATCH_NAMESPACE
              value: managed
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "governance-policy-spec-sync"
      volumes:
        - name: klusterlet-config
          secret:
            secretName: hub-kubeconfig
            defaultMode: 420