apiVersion: apps/v1
kind: Deployment
metadata:
  name: governance-policy-template-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      name: governance-policy-template-sync
  template:
    metadata:
      labels:
        name: governance-policy-template-sync
    spec:
      serviceAccountName: governance-policy-template-sync
      containers:
        - name: governance-policy-template-sync
          image: quay.io/open-cluster-management/governance-policy-template-sync:latest-dev
          command:
          - governance-policy-template-sync
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: managed
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "governance-policy-template-sync"
