apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam-policy-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: iam-policy-controller
  template:
    metadata:
      labels:
        name: iam-policy-controller
    spec:
      serviceAccountName: iam-policy-controller
      imagePullSecrets:
        - name: multiclusterhub-operator-pull-secret
      containers:
        - name: iam-policy-controller
          image: quay.io/open-cluster-management/iam-policy-controller:latest-dev
          command:
          - iam-policy-controller
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: managed
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "iam-policy-controller"
